<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';require_once dirname(__DIR__) . '/plugin/sabri-security-center/src/Support/Sanitizer.php';require_once dirname(__DIR__) . '/plugin/sabri-security-center/src/Storage/AuditLogger.php';require_once dirname(__DIR__) . '/plugin/sabri-security-center/src/Storage/AuditGapStore.php';require_once dirname(__DIR__) . '/plugin/sabri-security-center/src/Storage/GovernanceRepository.php';
use Sabri\Platform\Security\Storage\AuditGapStore;use Sabri\Platform\Security\Storage\AuditLogger;use Sabri\Platform\Security\Storage\GovernanceRepository;
$n=0;function c47(bool $v,string $m):void{global $n;++$n;if(!$v){fwrite(STDERR,"FAIL: $m\n");exit(1);}}
$gaps=[];for($i=1;$i<=100;$i++){ $id=sprintf('47000000-0000-4000-8000-%012d',$i);$gaps[$id]=['reason'=>'decision_audit_failed','recorded_at'=>gmdate('c')]; }
$GLOBALS['wp_options']['spcrc_governance_audit_gap']=$gaps;
$decision='47000000-0000-4000-8000-000000000101';
$GLOBALS['wpdb']->governance[$decision]=['decision_uuid'=>$decision,'decision_type'=>'policy-exception','subject_key'=>'cycle47','module_key'=>'file-24-security-center','status'=>'approved','requester_user_id'=>8,'approver_user_id'=>7,'evidence_ref'=>'vault:decision47','rationale_hash'=>hash('sha256','r'),'requested_at'=>gmdate('Y-m-d H:i:s',time()-60),'expires_at'=>gmdate('Y-m-d H:i:s',time()+3600),'decided_at'=>gmdate('Y-m-d H:i:s'),'revoked_at'=>null,'lock_version'=>1];
$repo=new GovernanceRepository(new AuditLogger());$rm=new ReflectionMethod($repo,'recordAuditGap');$rm->setAccessible(true);c47($rm->invoke($repo,$decision,'decision_audit_failed')===true,'Specific-gap capacity exhaustion must fall back to the centralized gap store.');c47(count(get_option('spcrc_governance_audit_gap',[]))===100,'Capacity fallback must not evict unresolved specific governance gaps.');c47($repo->hasAuditGap($decision),'Fallback governance audit gap must fail closed for the exact decision.');$batch=AuditGapStore::all('spcrc_governance_batch_audit_gap');c47(count($batch)===1,'Fallback gap must persist exactly once.');$entry=current($batch);c47(($entry['entity_id']??'')===$decision,'Fallback gap must remain bound to the exact decision UUID.');
$GLOBALS['current_user_caps']['spcrc_approve_governance_decision']=true;add_filter('spcrc/verify_step_up_assurance',static fn($ok,$actor,$purpose,$ref)=>$actor===7&&in_array($purpose,['governance:audit-reconciliation','audit-gap-reconciliation'],true)&&$ref==='file00:cycle47',10,4);
$reconciled=$repo->reconcileAuditGap($decision,['step_up_reference'=>'file00:cycle47','evidence_ref'=>'vault:cycle47-reconciliation','note'=>'Independent evidence reconciliation completed.']);c47($reconciled===true,'Authorized evidence-bound fallback reconciliation must succeed.');c47(!$repo->hasAuditGap($decision),'Successful fallback reconciliation must clear only the exact decision gap.');c47(AuditGapStore::count('spcrc_governance_batch_audit_gap')===0,'Reconciled fallback evidence must be removed durably.');
echo "PASS: $n Cycle 47 governance-gap reconciliation assertions\n";
